/**************************************************************************
**
** This file is part of Qt Creator
**
** Copyright (c) 2011 Nokia Corporation and/or its subsidiary(-ies).
**
** Contact: Nokia Corporation (info@qt.nokia.com)
**
**
** GNU Lesser General Public License Usage
**
** This file may be used under the terms of the GNU Lesser General Public
** License version 2.1 as published by the Free Software Foundation and
** appearing in the file LICENSE.LGPL included in the packaging of this file.
** Please review the following information to ensure the GNU Lesser General
** Public License version 2.1 requirements will be met:
** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain additional
** rights. These rights are described in the Nokia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** Other Usage
**
** Alternatively, this file may be used in accordance with the terms and
** conditions contained in a signed written agreement between you and Nokia.
**
** If you have questions regarding the use of this file, please contact
** Nokia at qt-info@nokia.com.
**
**************************************************************************/

//
//  W A R N I N G
//  -------------
//
// This file is automatically generated.
// Changes will be lost.
//


#include "RdbAST.h"
#include "RdbASTVisitor.h"

using namespace RDB;

void TranslationUnitAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(statement_list, visitor);
    }
    visitor->endVisit(this);
}

void SelectStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(select_core_list, visitor);
        accept(select_compound_list, visitor);
        accept(order_by_block, visitor);
        accept(limit_to_block, visitor);
    }
    visitor->endVisit(this);
}

void SelectCoreAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(columnList, visitor);
        accept(joinSource, visitor);
        accept(whereExpr, visitor);
        accept(groupBy, visitor);
    }
    visitor->endVisit(this);
}

void InvalidStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void UnknownStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SelectCompoundUnionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SelectCompoundIntersectAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SelectCompoundExceptAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SelectCompoundMinusAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void OrderByBlockAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(term_list, visitor);
    }
    visitor->endVisit(this);
}

void LimitToBlockAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(expr, visitor);
    }
    visitor->endVisit(this);
}

void OrderingTermAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(expr, visitor);
    }
    visitor->endVisit(this);
}

void SchemaNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void TableNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ViewNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void IndexNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void TriggerNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ConstraintNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}
void CursorNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void StorageMapNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void AreaNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SchemaTableNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaName, visitor);
        accept(tableName, visitor);
    }
    visitor->endVisit(this);

}

void SchemaIndexNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaName, visitor);
        accept(indexName, visitor);
    }
    visitor->endVisit(this);
}

void SchemaTriggerNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaName, visitor);
        accept(triggerName, visitor);
    }
    visitor->endVisit(this);
}

void TableAliasAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ColumnNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaName, visitor);
        accept(tableOfColumn, visitor);
    }
    visitor->endVisit(this);
}

void IdentifierNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ParamNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void LabelNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ColumnAliasAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void ModuleNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void RoutineNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void StarResultColumnAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
    }
    visitor->endVisit(this);
}

void ExprResultColumnAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(expr, visitor);
        accept(columnAlias, visitor);
    }
    visitor->endVisit(this);
}

void SubQueryAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(selectStatement, visitor);
    }
    visitor->endVisit(this);
}

void DirectSingleSourceAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
        accept(tableAlias, visitor);
    }
    visitor->endVisit(this);
}

void SubQuerySingleSourceAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(subQuery, visitor);
        accept(tableAlias, visitor);
    }
    visitor->endVisit(this);
}

void JoinOpAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void JoinConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(expr, visitor);
    }
    visitor->endVisit(this);
}

void JoinItemAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(joinOp, visitor);
        accept(singleSource, visitor);
        accept(joinConstraint, visitor);
    }
    visitor->endVisit(this);
}

void JoinSourceAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(firstSource, visitor);
        accept(source_list, visitor);
    }
    visitor->endVisit(this);
}

void GroupByBlockAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(group_items_list, visitor);
        accept(havingExpr, visitor);
    }
    visitor->endVisit(this);
}

void DeleteStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(source, visitor);
        accept(whereExpr, visitor);
    }
    visitor->endVisit(this);
}

void InsertStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(source, visitor);
        accept(columns_list, visitor);
        accept(insClause, visitor);
    }
    visitor->endVisit(this);
}

void UpdateStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(source, visitor);
        accept(upd_list, visitor);
        accept(whereExpr, visitor);
    }
    visitor->endVisit(this);
}

void CreateTableDirectClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(column_def_list, visitor);
        accept(constraintList, visitor);
    }
    visitor->endVisit(this);
}

void CreateTableAsSelectClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(selectStatement, visitor);
    }
    visitor->endVisit(this);
}

void CreateTriggerRefClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(newAlias, visitor);
        accept(oldAlias, visitor);
    }
    visitor->endVisit(this);
}

void CreateRdbTriggerBodyAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(item_list, visitor);
    }
    visitor->endVisit(this);
}

void CreateRdbTriggerBodyItemAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(whenExpr, visitor);
        accept(stat_list, visitor);
    }
    visitor->endVisit(this);
}

void ColumnDefinitionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(columnName, visitor);
        accept(columnType, visitor);
        accept(defaultExpr, visitor);
        accept(constraintList, visitor);
    }
    visitor->endVisit(this);
}

void UniqueOrPkTableConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
        accept(column_list, visitor);
    }
    visitor->endVisit(this);
}

void CheckTableConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
        accept(checkExpr, visitor);
    }
    visitor->endVisit(this);
}

void FkTableConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
        accept(col_list, visitor);
        accept(refClause, visitor);
    }
    visitor->endVisit(this);
}

void FkReferencesClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(refSchemaTableName, visitor);
        accept(ref_col_list, visitor);
    }
    visitor->endVisit(this);
}

void PkColumnConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
    }
    visitor->endVisit(this);
}

void NotNullColumnConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
    }
    visitor->endVisit(this);
}

void UniqueColumnConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
    }
    visitor->endVisit(this);
}

void CheckColumnConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
        accept(checkExpr, visitor);
    }
    visitor->endVisit(this);
}

void ReferencesColumnConstraintAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraintName, visitor);
        accept(refClause, visitor);
    }
    visitor->endVisit(this);
}

void SortedColumnNameAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(columnName, visitor);
    }
    visitor->endVisit(this);
}

void InsertClauseAsValuesAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(val_list, visitor);
    }
    visitor->endVisit(this);
}

void InsertClauseAsSelectAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(selectStatement, visitor);
    }
    visitor->endVisit(this);
}

void CreateTableStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
        accept(tableClause, visitor);
    }
    visitor->endVisit(this);
}

void CreateViewStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaViewName, visitor);
        accept(selectStatement, visitor);
    }
    visitor->endVisit(this);
}

void IndexTypeAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void IndexNodeSizeAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(sizeExpr, visitor);
    }
    visitor->endVisit(this);
}

void IndexStoreInAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(areaName, visitor);
    }
    visitor->endVisit(this);
}

void IndexOptionsAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(typeAst, visitor);
        accept(nodeSizeAst, visitor);
        accept(storeInAst, visitor);
    }
    visitor->endVisit(this);
}

void CreateIndexStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaIndexName, visitor);
        accept(schemaTableName, visitor);
        accept(columns_list, visitor);
        accept(options, visitor);
    }
    visitor->endVisit(this);
}

void CreateTriggerStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTriggerName, visitor);
        accept(schemaTableName, visitor);
        accept(col_list, visitor);
        accept(triggerRefClause, visitor);
        accept(triggerBody, visitor);
    }
    visitor->endVisit(this);
}

void CreateStorageMapStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(mapName, visitor);
        accept(tableName, visitor);
        accept(areaName, visitor);
    }
    visitor->endVisit(this);
}

void CreateModuleStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(moduleName, visitor);
        accept(commentExpr, visitor);
        accept(routine_list, visitor);
    }
    visitor->endVisit(this);
}

void CreateRoutineStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(routine, visitor);
    }
    visitor->endVisit(this);
}

void RoutineAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(routineName, visitor);
        accept(arg_list, visitor);
        accept(returnType, visitor);
        accept(block, visitor);
    }
    visitor->endVisit(this);
}

void DropTableStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
    }
    visitor->endVisit(this);
}

void DropViewStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaViewName, visitor);
    }
    visitor->endVisit(this);
}

void DropIndexStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaIndexName, visitor);
    }
    visitor->endVisit(this);
}

void DropTriggerStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTriggerName, visitor);
    }
    visitor->endVisit(this);
}

void DropModuleStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(moduleName, visitor);
    }
    visitor->endVisit(this);
}

void TruncateStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
    }
    visitor->endVisit(this);
}

void AlterTableStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
        accept(alterTableClause, visitor);
    }
    visitor->endVisit(this);
}

void AlterTableDropClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(dropObjectName, visitor);
    }
    visitor->endVisit(this);
}

void AlterTableAddConstraintClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(constraint, visitor);
    }
    visitor->endVisit(this);
}

void AlterTableAddColumnClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(column, visitor);
    }
    visitor->endVisit(this);
}

void CommentOnTableStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
    }
    visitor->endVisit(this);
}

void CommentOnColumnStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(schemaTableName, visitor);
        accept(column, visitor);
    }
    visitor->endVisit(this);
}

void CommitStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void RollbackStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void CallStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(funcName, visitor);
        accept(arg_list, visitor);
    }
    visitor->endVisit(this);
}

void BlockStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(decl_list, visitor);
        accept(entry_list, visitor);
    }
    visitor->endVisit(this);
}

void CharacterTypeAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void NumberTypeAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SimpleTypeAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void CompoundValueExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(valExpr, visitor);
    }
    visitor->endVisit(this);
}

void UnaryValueExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(valExpr, visitor);
    }
    visitor->endVisit(this);
}

void BinaryValueExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvExpr, visitor);
        accept(rvExpr, visitor);
    }
    visitor->endVisit(this);
}

void ColumnExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(column, visitor);
    }
    visitor->endVisit(this);
}

void LiteralExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void NumericExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void FunctionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(functionName, visitor);
        accept(arg_list, visitor);
    }
    visitor->endVisit(this);
}

void CastFunctionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(castExpr, visitor);
        accept(typeSpec, visitor);
    }
    visitor->endVisit(this);
}

void SubstringFunctionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(strExpr, visitor);
        accept(startExpr, visitor);
        accept(lengthExpr, visitor);
    }
    visitor->endVisit(this);
}

void CountFunctionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(countExpr, visitor);
    }
    visitor->endVisit(this);
}

void ParameterExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(binding, visitor);
    }
    visitor->endVisit(this);
}

void IdentifierExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(ident, visitor);
    }
    visitor->endVisit(this);
}

void IdentDotColumnExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(ident, visitor);
        accept(columnName, visitor);
    }
    visitor->endVisit(this);
}

void NullValueExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void SelectCompoundValueExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(query, visitor);
    }
    visitor->endVisit(this);
}

void ValueListExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(val_list, visitor);
    }
    visitor->endVisit(this);
}

void SubQueryExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(query, visitor);
    }
    visitor->endVisit(this);
}

void CompoundConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(condExpr, visitor);
    }
    visitor->endVisit(this);
}

void InConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvExpr, visitor);
        accept(rvExpr, visitor);
    }
    visitor->endVisit(this);
}

void LikeConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvExpr, visitor);
        accept(rvExpr, visitor);
    }
    visitor->endVisit(this);
}

void ExistsConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(rvExpr, visitor);
    }
    visitor->endVisit(this);
}

void BetweenConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvExpr, visitor);
        accept(rv1Expr, visitor);
        accept(rv2Expr, visitor);
    }
    visitor->endVisit(this);
}

void UnaryConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvExpr, visitor);
    }
    visitor->endVisit(this);
}
void BinaryConditionExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(lvCondExpr, visitor);
        accept(rvCondExpr, visitor);
    }
    visitor->endVisit(this);
}

void AssignmentExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(columnName, visitor);
        accept(rvExpr, visitor);
    }
    visitor->endVisit(this);
}

void CaseExpressionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(caseExpr, visitor);
        accept(var_list, visitor);
        accept(elseExpr, visitor);
    }
    visitor->endVisit(this);
}

void CaseExpressionClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(whenExpr, visitor);
        accept(thenExpr, visitor);
    }
    visitor->endVisit(this);
}

void CaseConditionAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(var_list, visitor);
        accept(elseExpr, visitor);
    }
    visitor->endVisit(this);
}

void CaseConditionClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(whenExpr, visitor);
        accept(thenExpr, visitor);
    }
    visitor->endVisit(this);
}

void DeclareAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(identName, visitor);
        accept(identType, visitor);
        accept(defaulExpr, visitor);
    }
    visitor->endVisit(this);
}

void ArgumentAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(ident, visitor);
        accept(identType, visitor);
    }
    visitor->endVisit(this);
}

void BlockInsertStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(insertStatement, visitor);
    }
    visitor->endVisit(this);
}

void BlockUpdateStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(updateStatement, visitor);
    }
    visitor->endVisit(this);
}

void BlockDeleteStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(deleteStatement, visitor);
    }
    visitor->endVisit(this);
}

void BlockSelectStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(columnList, visitor);
        accept(into_list, visitor);
        accept(joinSource, visitor);
        accept(whereExpr, visitor);
        accept(groupBy, visitor);
        accept(limit_to_block, visitor);
    }
    visitor->endVisit(this);
}

void BlockSetStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(ident, visitor);
        accept(assignExpr, visitor);
    }
    visitor->endVisit(this);
}

void BlockCommitStatmentAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void BlockRollbackStatmentAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
    }
    visitor->endVisit(this);
}

void BlockCallStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(callExpr, visitor);
    }
    visitor->endVisit(this);
}

void IfStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(conditionExpr, visitor);
        accept(then_entry_list, visitor);
        accept(else_entry_list, visitor);
    }
    visitor->endVisit(this);
}

void LoopStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(whileExpr, visitor);
        accept(entry_list, visitor);
    }
    visitor->endVisit(this);
}

void DeclareCursorClauseAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(cursorName, visitor);
    }
    visitor->endVisit(this);
}

void ForStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(forName, visitor);
        accept(cursor, visitor);
        accept(selectStatement, visitor);
        accept(entry_list, visitor);
    }
    visitor->endVisit(this);
}

void BlockLabelAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(labelName, visitor);
    }
    visitor->endVisit(this);
}

void LeaveStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(labelName, visitor);
    }
    visitor->endVisit(this);
}

void BlockBlockStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(block, visitor);
    }
    visitor->endVisit(this);
}

void BlockReturnStatementAST::accept0( ASTVisitor *visitor )
{
    if ( visitor->visit(this) ) {
        accept(returnExpr, visitor);
    }
    visitor->endVisit(this);
}
