/****************************************************************************
**
** Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
** Contact: http://www.qt-project.org/legal
**
** This file is part of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:LGPL$
** Commercial License Usage
** Licensees holding valid commercial Qt licenses may use this file in
** accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and Digia.  For licensing terms and
** conditions see http://qt.digia.com/licensing.  For further information
** use the contact form at http://qt.digia.com/contact-us.
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Digia gives you certain additional
** rights.  These rights are described in the Digia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3.0 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU General Public License version 3.0 requirements will be
** met: http://www.gnu.org/copyleft/gpl.html.
**
**
** $QT_END_LICENSE$
**
****************************************************************************/

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists for the convenience
// of other Qt classes.  This header file may change from version to
// version without notice, or even be removed.
//
// We mean it.
//

// This file was generated by qlalr - DO NOT EDIT!
#ifndef QLALRORACLEPARSERTABLE_P_H
#define QLALRORACLEPARSERTABLE_P_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

class QLalrOracleParserTable
{
public:
  enum VariousConstants {
    EOF_SYMBOL = 0,
    T_QLO_ABSOLUTE = 281,
    T_QLO_ACTION = 197,
    T_QLO_ADD = 81,
    T_QLO_AFTER = 148,
    T_QLO_ALL = 82,
    T_QLO_ALLOCATE = 282,
    T_QLO_ALTER = 149,
    T_QLO_AMPER = 39,
    T_QLO_AND = 83,
    T_QLO_ANY = 84,
    T_QLO_ARE = 85,
    T_QLO_ARRAY = 150,
    T_QLO_AS = 68,
    T_QLO_ASC = 86,
    T_QLO_ASENSITIVE = 331,
    T_QLO_ASSERTION = 307,
    T_QLO_ASSIGN = 42,
    T_QLO_ASYMMETRIC = 332,
    T_QLO_AT = 69,
    T_QLO_ATOMIC = 198,
    T_QLO_AUTHORIZATION = 360,
    T_QLO_BEFORE = 199,
    T_QLO_BEGIN = 151,
    T_QLO_BETWEEN = 243,
    T_QLO_BINARY = 26,
    T_QLO_BIT = 15,
    T_QLO_BITMAP = 200,
    T_QLO_BLOB = 17,
    T_QLO_BODY = 101,
    T_QLO_BOOLEAN = 29,
    T_QLO_BOTH = 102,
    T_QLO_BREADTH = 244,
    T_QLO_BUILTIN_FUNC = 14,
    T_QLO_BULK = 103,
    T_QLO_BY = 70,
    T_QLO_CALL = 104,
    T_QLO_CARET = 40,
    T_QLO_CASCADE = 245,
    T_QLO_CASCADED = 283,
    T_QLO_CASE = 105,
    T_QLO_CATALOG = 246,
    T_QLO_CHAR = 18,
    T_QLO_CHARACTER = 38,
    T_QLO_CHARSTR = 8,
    T_QLO_CHECK = 152,
    T_QLO_CLOB = 19,
    T_QLO_CLOSE = 153,
    T_QLO_COLLATE = 247,
    T_QLO_COLLATION = 308,
    T_QLO_COLLECT = 248,
    T_QLO_COLON = 41,
    T_QLO_COLUMN = 201,
    T_QLO_COMMA = 43,
    T_QLO_COMMENT = 249,
    T_QLO_COMMIT = 202,
    T_QLO_CONDITION = 309,
    T_QLO_CONNECT = 250,
    T_QLO_CONNECTION = 333,
    T_QLO_CONST = 154,
    T_QLO_CONSTANT = 284,
    T_QLO_CONSTRAINT = 334,
    T_QLO_CONSTRAINTS = 343,
    T_QLO_CONSTRUCTOR = 344,
    T_QLO_CONTINUE = 285,
    T_QLO_CORRESPONDING = 361,
    T_QLO_COUNT = 13,
    T_QLO_CREATE = 203,
    T_QLO_CROSS = 155,
    T_QLO_CUBE = 106,
    T_QLO_CURRENT = 251,
    T_QLO_CURRENT_DATE = 351,
    T_QLO_CURRENT_PATH = 352,
    T_QLO_CURRENT_ROLE = 353,
    T_QLO_CURRENT_TIME = 354,
    T_QLO_CURRENT_TIMESTAMP = 366,
    T_QLO_CURRENT_USER = 355,
    T_QLO_CURSOR = 204,
    T_QLO_CYCLE = 156,
    T_QLO_DASH = 58,
    T_QLO_DATA = 107,
    T_QLO_DATE = 20,
    T_QLO_DEALLOCATE = 335,
    T_QLO_DEC = 87,
    T_QLO_DECIMAL = 30,
    T_QLO_DECLARE = 252,
    T_QLO_DEFAULT = 253,
    T_QLO_DEFERRABLE = 336,
    T_QLO_DEFERRED = 286,
    T_QLO_DELETE = 205,
    T_QLO_DEPTH = 157,
    T_QLO_DEREF = 158,
    T_QLO_DESC = 108,
    T_QLO_DESCRIBE = 287,
    T_QLO_DESCRIPTOR = 337,
    T_QLO_DETERMINISTIC = 362,
    T_QLO_DIAGNOSTICS = 345,
    T_QLO_DISCONNECT = 338,
    T_QLO_DISTINCT = 288,
    T_QLO_DO = 71,
    T_QLO_DOMAIN = 206,
    T_QLO_DOT = 45,
    T_QLO_DOTDOT = 46,
    T_QLO_DOUBLE = 27,
    T_QLO_DROP = 109,
    T_QLO_DYNAMIC = 254,
    T_QLO_EACH = 110,
    T_QLO_ELSE = 111,
    T_QLO_ELSEIF = 207,
    T_QLO_END = 88,
    T_QLO_EQUAL = 47,
    T_QLO_EQUALS = 208,
    T_QLO_ERROR = 4,
    T_QLO_ESCAPE = 209,
    T_QLO_EXCEPT = 210,
    T_QLO_EXCEPTION = 310,
    T_QLO_EXCLAIM = 48,
    T_QLO_EXCLAIM_EQUAL = 49,
    T_QLO_EXEC = 112,
    T_QLO_EXECUTE = 255,
    T_QLO_EXISTS = 211,
    T_QLO_EXIT = 113,
    T_QLO_EXTERNAL = 289,
    T_QLO_FALSE = 11,
    T_QLO_FEED_EXPRESSION = 2,
    T_QLO_FEED_ORACLE = 1,
    T_QLO_FEED_STATEMENT = 3,
    T_QLO_FETCH = 159,
    T_QLO_FILTER = 212,
    T_QLO_FLOAT = 23,
    T_QLO_FOR = 89,
    T_QLO_FORCE = 160,
    T_QLO_FOREIGN = 256,
    T_QLO_FREE = 114,
    T_QLO_FROM = 115,
    T_QLO_FULL = 116,
    T_QLO_FUNCTION = 290,
    T_QLO_GENERAL = 257,
    T_QLO_GET = 90,
    T_QLO_GLOBAL = 213,
    T_QLO_GO = 72,
    T_QLO_GOTO = 117,
    T_QLO_GRANT = 161,
    T_QLO_GREATER = 50,
    T_QLO_GREATER_EQUAL = 51,
    T_QLO_GROUP = 162,
    T_QLO_GROUPING = 291,
    T_QLO_GROUP_FUNC = 12,
    T_QLO_HANDLER = 258,
    T_QLO_HAVING = 214,
    T_QLO_HOLD = 118,
    T_QLO_IDENTIFIER = 5,
    T_QLO_IDENTITY = 292,
    T_QLO_IF = 73,
    T_QLO_IMMEDIATE = 311,
    T_QLO_IN = 74,
    T_QLO_INDEX = 163,
    T_QLO_INDICATOR = 312,
    T_QLO_INITIALLY = 313,
    T_QLO_INNER = 164,
    T_QLO_INOUT = 165,
    T_QLO_INPUT = 166,
    T_QLO_INSENSITIVE = 346,
    T_QLO_INSERT = 215,
    T_QLO_INT = 16,
    T_QLO_INTEGER = 31,
    T_QLO_INTERSECT = 314,
    T_QLO_INTERVAL = 293,
    T_QLO_INTO = 119,
    T_QLO_IS = 75,
    T_QLO_ISOLATION = 315,
    T_QLO_ITERATE = 259,
    T_QLO_JOIN = 120,
    T_QLO_KEY = 91,
    T_QLO_LANGUAGE = 294,
    T_QLO_LARGE = 167,
    T_QLO_LATERAL = 260,
    T_QLO_LEADING = 261,
    T_QLO_LEAVE = 168,
    T_QLO_LEFT = 121,
    T_QLO_LEFT_BRACE = 52,
    T_QLO_LEFT_BRACKET = 53,
    T_QLO_LEFT_PAREN = 57,
    T_QLO_LESS = 54,
    T_QLO_LESS_EQUAL = 55,
    T_QLO_LESS_GREATER = 56,
    T_QLO_LEVEL = 169,
    T_QLO_LIKE = 122,
    T_QLO_LIMIT = 170,
    T_QLO_LOCAL = 171,
    T_QLO_LOCALTIME = 316,
    T_QLO_LOCALTIMESTAMP = 364,
    T_QLO_LOCATOR = 262,
    T_QLO_LOCK = 123,
    T_QLO_LOOP = 124,
    T_QLO_MAP = 92,
    T_QLO_MATCH = 172,
    T_QLO_METHOD = 216,
    T_QLO_MINUS = 173,
    T_QLO_MODIFIES = 295,
    T_QLO_MODULE = 217,
    T_QLO_NAMES = 174,
    T_QLO_NATIONAL = 35,
    T_QLO_NATURAL = 32,
    T_QLO_NCHAR = 24,
    T_QLO_NCLOB = 25,
    T_QLO_NEW = 93,
    T_QLO_NEXT = 125,
    T_QLO_NO = 76,
    T_QLO_NONE = 126,
    T_QLO_NORELY = 218,
    T_QLO_NOT = 94,
    T_QLO_NOWAIT = 219,
    T_QLO_NULL = 127,
    T_QLO_NULL_IDENTIFIER = 6,
    T_QLO_NUMBER = 7,
    T_QLO_NUMERIC = 33,
    T_QLO_OBJECT = 28,
    T_QLO_OF = 77,
    T_QLO_OLD = 95,
    T_QLO_ON = 78,
    T_QLO_ONLY = 128,
    T_QLO_OPEN = 129,
    T_QLO_OPTION = 220,
    T_QLO_OR = 79,
    T_QLO_ORDER = 175,
    T_QLO_ORDINALITY = 339,
    T_QLO_OUT = 96,
    T_QLO_OUTER = 176,
    T_QLO_OUTPUT = 221,
    T_QLO_OVER = 130,
    T_QLO_OVERLAPS = 296,
    T_QLO_PACKAGE = 263,
    T_QLO_PARAMETER = 317,
    T_QLO_PARTIAL = 264,
    T_QLO_PARTITION = 318,
    T_QLO_PATH = 131,
    T_QLO_PERCENT = 59,
    T_QLO_PIPE = 60,
    T_QLO_PIPELINED = 319,
    T_QLO_PIPE_PIPE = 61,
    T_QLO_PLUS = 62,
    T_QLO_PRECISION = 320,
    T_QLO_PREPARE = 265,
    T_QLO_PRESERVE = 297,
    T_QLO_PRIMARY = 266,
    T_QLO_PRIOR = 177,
    T_QLO_PRIVILEGES = 340,
    T_QLO_PROCEDURE = 321,
    T_QLO_PUBLIC = 222,
    T_QLO_RANGE = 178,
    T_QLO_READ = 132,
    T_QLO_READS = 179,
    T_QLO_REAL = 134,
    T_QLO_RECORD = 223,
    T_QLO_RECURSIVE = 322,
    T_QLO_REF = 97,
    T_QLO_REFERENCES = 341,
    T_QLO_REFERENCING = 347,
    T_QLO_RELATIVE = 298,
    T_QLO_RELEASE = 267,
    T_QLO_RELIES_ON = 323,
    T_QLO_RELY = 133,
    T_QLO_REPEAT = 224,
    T_QLO_REPLACE = 268,
    T_QLO_RESIGNAL = 299,
    T_QLO_RESTRICT = 300,
    T_QLO_RESULT = 225,
    T_QLO_RESULT_CACHE = 356,
    T_QLO_RETURN = 226,
    T_QLO_RETURNING = 324,
    T_QLO_RETURNS = 269,
    T_QLO_REVOKE = 227,
    T_QLO_RIGHT = 180,
    T_QLO_RIGHT_BRACE = 63,
    T_QLO_RIGHT_BRACKET = 64,
    T_QLO_RIGHT_PAREN = 65,
    T_QLO_ROLE = 135,
    T_QLO_ROLLBACK = 301,
    T_QLO_ROLLUP = 228,
    T_QLO_ROUTINE = 270,
    T_QLO_ROW = 98,
    T_QLO_ROWS = 136,
    T_QLO_ROWTYPE = 271,
    T_QLO_SAVEPOINT = 325,
    T_QLO_SCHEMA = 229,
    T_QLO_SCOPE = 181,
    T_QLO_SCROLL = 230,
    T_QLO_SEARCH = 231,
    T_QLO_SECTION = 272,
    T_QLO_SELECT = 232,
    T_QLO_SEMICOLON = 66,
    T_QLO_SENSITIVE = 326,
    T_QLO_SESSION = 273,
    T_QLO_SESSION_USER = 357,
    T_QLO_SET = 99,
    T_QLO_SETS = 137,
    T_QLO_SIGNAL = 233,
    T_QLO_SIMILAR = 274,
    T_QLO_SLASH = 44,
    T_QLO_SMALLINT = 36,
    T_QLO_SOME = 138,
    T_QLO_SPACE = 182,
    T_QLO_SPECIFIC = 302,
    T_QLO_SPECIFICTYPE = 358,
    T_QLO_SQL = 100,
    T_QLO_SQLEXCEPTION = 359,
    T_QLO_SQLSTATE = 303,
    T_QLO_SQLWARNING = 342,
    T_QLO_STAR = 67,
    T_QLO_START = 183,
    T_QLO_STATE = 184,
    T_QLO_STATEMENT = 327,
    T_QLO_STATIC = 234,
    T_QLO_STORAGE = 275,
    T_QLO_STORE = 185,
    T_QLO_STRSTR = 9,
    T_QLO_SUBTYPE = 276,
    T_QLO_SYMMETRIC = 328,
    T_QLO_SYSTEM = 235,
    T_QLO_SYSTEM_USER = 348,
    T_QLO_TABLE = 186,
    T_QLO_TEMPORARY = 329,
    T_QLO_THEN = 139,
    T_QLO_TIME = 140,
    T_QLO_TIMESTAMP = 330,
    T_QLO_TIMEZONE_HOUR = 363,
    T_QLO_TIMEZONE_MINUTE = 365,
    T_QLO_TO = 80,
    T_QLO_TRAILING = 304,
    T_QLO_TRANSACTION = 349,
    T_QLO_TRANSLATION = 350,
    T_QLO_TREAT = 187,
    T_QLO_TRIGGER = 277,
    T_QLO_TRUE = 10,
    T_QLO_TRUNCATE = 305,
    T_QLO_TYPE = 141,
    T_QLO_UNDER = 188,
    T_QLO_UNDO = 142,
    T_QLO_UNION = 189,
    T_QLO_UNIQUE = 236,
    T_QLO_UNKNOWN = 278,
    T_QLO_UNNEST = 237,
    T_QLO_UNTIL = 190,
    T_QLO_UPDATE = 238,
    T_QLO_USAGE = 191,
    T_QLO_USER = 143,
    T_QLO_USING = 192,
    T_QLO_VALUE = 193,
    T_QLO_VALUES = 239,
    T_QLO_VARCHAR = 34,
    T_QLO_VARCHAR2 = 37,
    T_QLO_VARRAY = 240,
    T_QLO_VARYING = 279,
    T_QLO_VIEW = 144,
    T_QLO_WHEN = 145,
    T_QLO_WHENEVER = 306,
    T_QLO_WHERE = 194,
    T_QLO_WHILE = 195,
    T_QLO_WINDOW = 241,
    T_QLO_WITH = 146,
    T_QLO_WITHIN = 242,
    T_QLO_WITHOUT = 280,
    T_QLO_WORK = 147,
    T_QLO_WRITE = 196,
    T_QLO_YEAR = 21,
    T_QLO_ZONE = 22,

    ACCEPT_STATE = 607,
    RULE_COUNT = 313,
    STATE_COUNT = 608,
    TERMINAL_COUNT = 367,
    NON_TERMINAL_COUNT = 101,

    GOTO_INDEX_OFFSET = 608,
    GOTO_INFO_OFFSET = 1699,
    GOTO_CHECK_OFFSET = 1699
  };

  static const char  *const    spell [];
  static const short             lhs [];
  static const short             rhs [];
  static const short    goto_default [];
  static const short  action_default [];
  static const short    action_index [];
  static const short     action_info [];
  static const short    action_check [];

  static inline int nt_action (int state, int nt)
  {
    const int yyn = action_index [GOTO_INDEX_OFFSET + state] + nt;
    if (yyn < 0 || action_check [GOTO_CHECK_OFFSET + yyn] != nt)
      return goto_default [nt];

    return action_info [GOTO_INFO_OFFSET + yyn];
  }

  static inline int t_action (int state, int token)
  {
    const int yyn = action_index [state] + token;

    if (yyn < 0 || action_check [yyn] != token)
      return - action_default [state];

    return action_info [yyn];
  }
};


QT_END_NAMESPACE
#endif // QLALRORACLEPARSERTABLE_P_H

