#ifndef PROFILEEDITOR_GLOBAL_H
#define PROFILEEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROFILEEDITOR_LIBRARY)
#  define PROFILEEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROFILEEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROFILEEDITOR_GLOBAL_H
